VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Controllers/UsersAdminController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VASTQuickShoping.Models.Identity;
using VASTQuickShoping.UI.Areas.Admin.ViewModels;
using VASTQuickShoping.UI.ViewModels;

namespace VASTQuickShoping.UI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.UserName, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UserName,Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.UserName;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Views/UsersAdmin/Create.cshtml
@model VASTQuickShoping.UI.ViewModels.RegisterViewModel
@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title.</h2>

<br />

<h1 style="color:red">Crea tu Usuario </h1>

<div class="col-sm-10 col-md-8 col-lg-6 card" style="background-color:#f1fbfc">

    <div class="text-center border border-light p-5" action="#!">
        @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {

            @Html.AntiForgeryToken()
            <h4>Cree una cuenta nueva.</h4>
            <hr />
           
           
            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "col-md-6 control-label" })
                <div class="col-md-12">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-6 control-label" })
                <div class="col-md-12">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-6 control-label" })
                <div class="col-md-12">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-6 control-label" })
                <div class="col-md-12">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

           <div class="form-group">
             <label class="col-md-8 control-label">
             Selecciona un rol
           </label>
               <div class="col-md-12">
              @foreach (var item in (SelectList) ViewBag.RoleId)
                {
                    <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                    @Html.Label(item.Value, new { @class = "control-label" })
                }
             </div>
                 </div>

            <!-- Sign in button -->

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <input type="submit" class="btn btn-info btn-block my-4" value="Crear" />
                </div>
            </div>


            <p>
                @Html.ActionLink("Registrarse como usuario nuevo", "Register")
            </p>
            @* Habilite esta opción una vez tenga la confirmación de la cuenta habilitada para la funcionalidad de restablecimiento de contraseña*@
            <p>
                @Html.ActionLink("¿Ha olvidado su contraseña?", "ForgotPassword")
            </p> <!-- Register -->


            <a href="#" class="mx-2" role="button"><i class="fab fa-facebook-f light-blue-text"></i></a>
            <a href="#" class="mx-2" role="button"><i class="fab fa-twitter light-blue-text"></i></a>
            <a href="#" class="mx-2" role="button"><i class="fab fa-linkedin-in light-blue-text"></i></a>
            <a href="#" class="mx-2" role="button"><i class="fab fa-github light-blue-text"></i></a>

        }

    </div>
</div>






@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Views/UsersAdmin/Delete.cshtml
@model VASTQuickShoping.Models.Identity.ApplicationUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete.</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <h4>User.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Views/UsersAdmin/Details.cshtml
@model VASTQuickShoping.Models.Identity.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>DETALLES</h2>

<div>
    <h4>USUARIO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="color:red">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<div class="container ">
    <h4 style="color:red">Lista de roles de usuario</h4>
    @if (ViewBag.RoleNames.Count == 0)
    {
        <hr />
        <p>No roles found for this user.</p>
    }
</div>

<div class="container card">
    <div class="row justify-content-center">
        <div class="col-sm-8">

            <table class=" table table-stripe table-hover">

                @foreach (var item in ViewBag.RoleNames)
                {
                    <tr>
                        <td>
                            @item
                        </td>
                    </tr>
                }

            </table>


            <p>
                <a href="~/Admin/usersadmin/Edit/@Model.Id"><img src="https://img.icons8.com/cute-clipart/35/000000/pencil.png" /></a>
                <a href="~/Admin/usersadmin/Index/"><img src="https://img.icons8.com/cute-clipart/35/000000/return.png" /></a>

            </p>
        </div>
    </div>
</div>

VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Views/UsersAdmin/Edit.cshtml
@model VASTQuickShoping.UI.Areas.Admin.ViewModels.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}


<div class="row  justify-content-center
">

    <div class="col-sm-10 col-md-8 col-lg-6 card" style="background-color:#f1fbfc">
        <div class="text-center border border-light p-5" action="#!">
            @using (Html.BeginForm())
            {

                @Html.AntiForgeryToken()
                <h4>Editar Usuarios administrativos.</h4>
                <hr />
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)
                <div class="form-group">
                    @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-6" })
                    <div class="col-md-12">
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UserName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-6" })
                    <div class="col-md-12">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
                <div class="form-group">
                   <p>Roles</p>
                   
                    <span class=" col-md-12">
                        @foreach (var item in Model.RolesList)
                        {
                            <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                            @Html.Label(item.Value, new { @class = "control-label" })
                        }
                    </span>
                </div>
                <!-- Sign in button -->

                <input type="submit" value="GUARDAR" class="btn btn-info btn-block my-4" />
            
            }
            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>

        </div>
    </div>
</div>












@**

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

VASTQuickShoping/VASTQuickShoping.UI/Areas/Admin/Views/UsersAdmin/Index.cshtml
@model IEnumerable<VASTQuickShoping.Models.Identity.ApplicationUser>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-danger">CREAR USUARIOS</h2>

<p>
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-sm-3">

                <a href="~/Admin/UsersAdmin/Create" class="btn btn-info btn-block my-4">Crear </a>
            </div>

        </div>

    </div>
</p>
<div class="container">
    <table class="table table-stripe table-hover">
        <thead style=" background-color: #3e4353" class="#">
            <tr>

                <th style="width:50%; color:white;">

                    @Html.DisplayNameFor(model => model.UserName)
                </th>

                <th style="width:30%">

                </th>

            </tr>

        </thead>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    <a href="~/Admin/usersadmin/Edit/@item.Id"><img src="https://img.icons8.com/cute-clipart/35/000000/pencil.png" /></a>
                    <a href="~/Admin/usersadmin/Details/@item.Id"><img src="https://img.icons8.com/cute-clipart/35/000000/book.png" /></a>
                    <a href="~/Admin/usersadmin/Delete/@item.Id"onclick="return confirm('¿Estas seguro de eliminar este registro?')"> <img src="https://img.icons8.com/fluent/35/000000/trash.png" /></a>

                </td>
            </tr>
        }


    </table>
</div>